language: node_js
node_js:
- '12'
- '10'
- '8'
sudo: true
cache:
  directories:
  - node_modules
before_install:
- npm i
script:
- npm run build
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: wangkangsen168@163.com
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: Pd1hhWae/fzKe+zir6U/f8VAjXI5iSOQAoKpdxthaUghhO+zD8uTmdiZkC7i4tbU27ZPRmMScgAWjfgOt25L1lF45UUJECbfh9J0gjsu+2z7qgsFdsIyol+w7zCI1JRZGRVho7rIhpnstgpPfQ2uvhbFfRhDUWllRBydsB4aqumxL65tFno51j0cYkrcAzsAcBPoUZFItbDSZFRjHI+we/DcmUOP24e7etJS1gSpf6Y1ZiBpAUFy5QwF8mJ7F50TnnJEqBeoNyMliFVlDMLN0uYRNwpquyMsih+UhX7xCfllBUS3/ppzumGxXFrNJwyfEfSKEAcZk57+KA1yZ2jycwwdLUUA7EcpmVdEzWp04D+4Uejmm+AT4aWi7eOJKKn8ZRHdhkvFWqMd9miU7yTkbzp+QWmyGeTYY/U8N259NF//tON51rbpcu5A45ElWrKRmVRGkmdgkbQlO+FX+MUYZ8pRVo2DVTKEJfgP1USu73bGgBYo5Rij750tsPY3e0PWLEkgmJ4A/NElnM8Gq9C8b2nFA/5H9Jd9JYaubL8ONrmBms93lAw1x515C7LAF2mWUz9CF+ARgnhuFce/zSmmQi8i7AizkHdQQzANYaX872xJB/lyxtAl7myKn64iSP6GpvgGSSUGvP/0pC+dV21cPTcjD9YooHLOYVAVd75pM3A=
env:
  global:
    secure: ibEqQUpC2mJzTvM2DWzXeL5Rh0hLs1HmCY83Pgpia7l40BK3MKR6TB574CRmCj7TXQ/wIqldQFe3+/iRrtawl/unvji59pCcBVJN2C0K9QpRcYj74DFPfsgbb6Z5YW/RzZPgm8NhKaTwAa/bZ8HMgNcatOFKnRlOpmXz92K4PkgFJMY0Z4eH4y8eOtH3Yc+HRezHvEYoQoqoWrwcWyXk6OVdQSrXeHi8nEsVF3pX4zu/gl66P02k4/bvDzVSnpN0Mt6myDwB/sMQlTGLDCW1dauNVzVQi/nXrnF1Ti7
      20+grpTTFln1CgNRyeUUhaG3OLy7ciUmTHxwSNHTkNHzUII4+fn3MvHWb/5CtasaqFo2f0hX1oJ8gsDWFCqTZgnYKMKjcdN4k1U1DqeRA1LKXyZt0wyZrQe/aMKWE7DQRRswEjrOBiD4n629z3EZXqsB9
      nUHFE45x4IowAeMSJ1G0YddBF9ikRwP5ufuxDweHxrPZf0nKqGmfpEysYONPLA4JAemkM8VlY5yiUNe/l+2UypdrXXu6Mf0OWToEq8cw+u2CtngLsdI+CjNUGeQJ55+NH0AqovUMHUDhED18Nnnj0LjZpmuf5mbKcljqpSyii/85PSGlZKY+erNUB+leQAp45DHniBASGQ2ccGFZsLBuI5rK3EE102tgJtY6cj9OH54=
